"""create initial tables

Revision ID: d66a43b0fead
Revises:
Create Date: 2026-07-11 13:42:14.237029

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d66a43b0fead"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "location",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column(
            "created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_location")),
    )
    op.create_table(
        "metric",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("unit", sa.String(), nullable=True),
        sa.Column(
            "created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_metric")),
    )
    op.create_index(op.f("ix_metric_name"), "metric", ["name"], unique=True)
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column(
            "created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "measurement",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("metric_id", sa.Integer(), nullable=False),
        sa.Column("ts_value", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ts_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("forecast_horizon", sa.Integer(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["location_id"], ["location.id"], name=op.f("fk_measurement_location_id_location")
        ),
        sa.ForeignKeyConstraint(
            ["metric_id"], ["metric.id"], name=op.f("fk_measurement_metric_id_metric")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_measurement")),
    )
    op.create_index(
        op.f("ix_measurement_location_id"), "measurement", ["location_id"], unique=False
    )
    op.create_index(op.f("ix_measurement_metric_id"), "measurement", ["metric_id"], unique=False)
    op.create_index(op.f("ix_measurement_ts_value"), "measurement", ["ts_value"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_measurement_ts_value"), table_name="measurement")
    op.drop_index(op.f("ix_measurement_metric_id"), table_name="measurement")
    op.drop_index(op.f("ix_measurement_location_id"), table_name="measurement")
    op.drop_table("measurement")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_metric_name"), table_name="metric")
    op.drop_table("metric")
    op.drop_table("location")
    # ### end Alembic commands ###
