apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Generate a secret from the .env file in the root of the project (Also used in python code to load environment variables)
secretGenerator:
  - name: weather-api-secret
    envs:
      - .env