apiVersion: batch/v1
kind: CronJob
metadata:
  name: weather-api-daily-forecast-ingest
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: daily-forecast-ingest
              image: ghcr.io/krantzy-dev/cc_weather_api:v0.8.3
              command: ["python", "-m", "src.load_data.daily_forecast_ingest"]
              envFrom:
                - secretRef:
                    name: weather-api-secret
              env:
                - name: POSTGRES_HOST
                  value: weather-api-postgres
                - name: POSTGRES_PORT
                  value: "5432"
          restartPolicy: OnFailure
