apiVersion: batch/v1
kind: CronJob
metadata:
  name: weather-api-hourly-ingest
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hourly-ingest
              image: ghcr.io/krantzy-dev/cc_weather_api:v0.8.1
              command: ["python", "-m", "src.load_data.hourly_ingest"]
              envFrom:
                - secretRef:
                    name: weather-api-secret
          restartPolicy: OnFailure
