apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: weather-api-postgres
spec:
  serviceName: weather-api-postgres
  replicas: 1
  selector:
    matchLabels:
      app: weather-api-postgres
  template:
    metadata:
      labels:
        app: weather-api-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:18.4-bookworm
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: weather-api-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: weather-api-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: weather-api-secret
                  key: POSTGRES_DB
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql
              subPath: pgdata
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi