apiVersion: v1
kind: Service
metadata:
  name: weather-api-postgres-external
spec:
  type: NodePort
  selector:
    app: weather-api-postgres
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30001